"""Add is_national to FormulaFordEventEntry

Revision ID: 36076ddc37b0
Revises: c7cc2707d48d
Create Date: 2025-10-03 09:45:34.762968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36076ddc37b0'
down_revision = 'c7cc2707d48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formula_ford_event_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_national', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formula_ford_event_entry', schema=None) as batch_op:
        batch_op.drop_column('is_national')

    # ### end Alembic commands ###
